name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]  # mise Ã  jour automatique toutes les 12h
  workflow_dispatch:                  # permet de le lancer manuellement
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics for Emmanuelsakpleto
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Emmanuelsakpleto
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Casablanca
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage, lines
          plugin_languages_limit: 8
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_stars: yes
