name: GitHub Metrics Auto Update

on:
  schedule:
    - cron: "0 0 * * *"  # chaque jour Ã  minuit
  workflow_dispatch:      # lancement manuel possible

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Emmanuelsakpleto
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Lome
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_limit: 5
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_calendar: yes
          plugin_calendar_limit: 1

      - name: Commit updated README
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Auto-update GitHub metrics" || echo "No changes to commit"
          git push
